/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.funding.channel'

export { $nsid }

/** A payment channel — a specific place where contributions can be received (e.g. a GitHub Sponsors page, an Open Collective profile, a bank account). Each channel is an independent record, individually addressable by its AT URI. */
type Main = {
  $type: 'fund.at.funding.channel'

  /**
   * Channel category. Maps to funding.json channel.type.
   */
  channelType:
    | 'payment-provider'
    | 'bank'
    | 'cheque'
    | 'cash'
    | 'other'
    | l.UnknownString

  /**
   * The payment URL for this channel (e.g. https://github.com/sponsors/you). Optional for channels without a public URL (e.g. bank transfers). Maps to funding.json channel.address.
   */
  uri?: l.UriString

  /**
   * Human-readable description of this channel.
   */
  description?: string

  /**
   * When this record was created or last updated.
   */
  createdAt?: l.DatetimeString
}

export type { Main }

/** A payment channel — a specific place where contributions can be received (e.g. a GitHub Sponsors page, an Open Collective profile, a bank account). Each channel is an independent record, individually addressable by its AT URI. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    channelType: l.string<{
      maxLength: 32
      knownValues: ['payment-provider', 'bank', 'cheque', 'cash', 'other']
    }>({ maxLength: 32 }),
    uri: l.optional(l.string({ format: 'uri' })),
    description: l.optional(l.string({ maxLength: 500 })),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
