/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.funding.contribute'

export { $nsid }

/** The steward's canonical funding entry point. A single URL where people can support this entity. */
type Main = {
  $type: 'fund.at.funding.contribute'

  /**
   * The canonical funding page URL (e.g. GitHub Sponsors, Open Collective, ko-fi, or a custom landing page).
   */
  url: l.UriString

  /**
   * When this record was created or last updated.
   */
  createdAt?: l.DatetimeString
}

export type { Main }

/** The steward's canonical funding entry point. A single URL where people can support this entity. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    url: l.string({ format: 'uri' }),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
