/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.funding.defs'

export { $nsid }

/** A single payment channel where contributions can be made. */
type Channel = {
  $type?: 'fund.at.funding.defs#channel'

  /**
   * Slug identifier for this channel, unique within the manifest (e.g. 'github-sponsors', 'open-collective').
   */
  channelId: string

  /**
   * Channel category.
   */
  channelType?: 'payment-provider' | 'bank' | 'other' | l.UnknownString

  /**
   * The payment URL for this channel (e.g. https://github.com/sponsors/you).
   */
  uri: l.UriString

  /**
   * Human-readable description of this channel.
   */
  description?: string
}

export type { Channel }

/** A single payment channel where contributions can be made. */
const channel = l.typedObject<Channel>(
  $nsid,
  'channel',
  l.object({
    channelId: l.string({ maxLength: 32 }),
    channelType: l.optional(
      l.string<{
        maxLength: 32
        knownValues: ['payment-provider', 'bank', 'other']
      }>({ maxLength: 32 }),
    ),
    uri: l.string({ format: 'uri' }),
    description: l.optional(l.string({ maxLength: 256 })),
  }),
)

export { channel }

/** A funding plan or tier with a suggested amount. */
type Plan = {
  $type?: 'fund.at.funding.defs#plan'

  /**
   * Slug identifier for this plan, unique within the manifest.
   */
  planId: string

  /**
   * Human-readable plan name (e.g. 'Supporter', 'Sustainer').
   */
  name: string

  /**
   * What this plan covers or how the funds are used.
   */
  description?: string

  /**
   * Suggested amount in the smallest currency unit (e.g. cents for USD). Use 0 for 'any amount'.
   */
  amount?: number

  /**
   * ISO 4217 currency code (e.g. 'USD', 'EUR').
   */
  currency?: string

  /**
   * How often the plan is billed.
   */
  frequency?: 'one-time' | 'monthly' | 'yearly' | 'other' | l.UnknownString

  /**
   * Channel IDs where this plan can be fulfilled. If omitted, all channels apply.
   */
  channels?: ChannelRef[]
}

export type { Plan }

/** A funding plan or tier with a suggested amount. */
const plan = l.typedObject<Plan>(
  $nsid,
  'plan',
  l.object({
    planId: l.string({ maxLength: 32 }),
    name: l.string({ maxLength: 128 }),
    description: l.optional(l.string({ maxLength: 256 })),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
    frequency: l.optional(
      l.string<{
        maxLength: 16
        knownValues: ['one-time', 'monthly', 'yearly', 'other']
      }>({ maxLength: 16 }),
    ),
    channels: l.optional(l.array(l.ref<ChannelRef>((() => channelRef) as any))),
  }),
)

export { plan }

/** A reference to a channel by its ID. */
type ChannelRef = {
  $type?: 'fund.at.funding.defs#channelRef'

  /**
   * The channelId of the referenced channel.
   */
  channelId: string
}

export type { ChannelRef }

/** A reference to a channel by its ID. */
const channelRef = l.typedObject<ChannelRef>(
  $nsid,
  'channelRef',
  l.object({ channelId: l.string({ maxLength: 32 }) }),
)

export { channelRef }
