/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.funding.defs'

export { $nsid }

/** A single payment channel where contributions can be made. Maps to a funding.json channel entry. */
type Channel = {
  $type?: 'fund.at.funding.defs#channel'

  /**
   * Slug identifier for this channel, unique within the manifest (e.g. 'github-sponsors', 'open-collective'). Maps to funding.json channel.guid.
   */
  channelId: string

  /**
   * Channel category. Maps to funding.json channel.type.
   */
  channelType?:
    | 'payment-provider'
    | 'bank'
    | 'cheque'
    | 'cash'
    | 'other'
    | l.UnknownString

  /**
   * The payment URL for this channel (e.g. https://github.com/sponsors/you). Optional for channels without a public URL (e.g. bank transfers). Maps to funding.json channel.address.
   */
  uri?: l.UriString

  /**
   * Human-readable description of this channel.
   */
  description?: string
}

export type { Channel }

/** A single payment channel where contributions can be made. Maps to a funding.json channel entry. */
const channel = l.typedObject<Channel>(
  $nsid,
  'channel',
  l.object({
    channelId: l.string({ maxLength: 32 }),
    channelType: l.optional(
      l.string<{
        maxLength: 32
        knownValues: ['payment-provider', 'bank', 'cheque', 'cash', 'other']
      }>({ maxLength: 32 }),
    ),
    uri: l.optional(l.string({ format: 'uri' })),
    description: l.optional(l.string({ maxLength: 500 })),
  }),
)

export { channel }

/** A funding plan or tier with a suggested amount. Maps to a funding.json plan entry. */
type Plan = {
  $type?: 'fund.at.funding.defs#plan'

  /**
   * Slug identifier for this plan, unique within the manifest. Maps to funding.json plan.guid.
   */
  planId: string

  /**
   * Whether this plan is currently accepting contributions. Maps to funding.json plan.status.
   */
  status?: 'active' | 'inactive' | l.UnknownString

  /**
   * Human-readable plan name (e.g. 'Supporter', 'Sustainer').
   */
  name: string

  /**
   * What this plan covers or how the funds are used.
   */
  description?: string

  /**
   * Suggested amount in the smallest currency unit (e.g. cents for USD). Use 0 for 'any amount'. Maps to funding.json plan.amount (converted from whole units).
   */
  amount?: number

  /**
   * ISO 4217 currency code (e.g. 'USD', 'EUR').
   */
  currency?: string

  /**
   * How often the plan is billed. Maps to funding.json plan.frequency.
   */
  frequency?:
    | 'one-time'
    | 'weekly'
    | 'fortnightly'
    | 'monthly'
    | 'yearly'
    | 'other'
    | l.UnknownString

  /**
   * Channel IDs where this plan can be fulfilled. If omitted, all channels apply. Maps to funding.json plan.channels.
   */
  channels?: ChannelRef[]
}

export type { Plan }

/** A funding plan or tier with a suggested amount. Maps to a funding.json plan entry. */
const plan = l.typedObject<Plan>(
  $nsid,
  'plan',
  l.object({
    planId: l.string({ maxLength: 32 }),
    status: l.optional(
      l.string<{ maxLength: 16; knownValues: ['active', 'inactive'] }>({
        maxLength: 16,
      }),
    ),
    name: l.string({ maxLength: 128 }),
    description: l.optional(l.string({ maxLength: 500 })),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
    frequency: l.optional(
      l.string<{
        maxLength: 16
        knownValues: [
          'one-time',
          'weekly',
          'fortnightly',
          'monthly',
          'yearly',
          'other',
        ]
      }>({ maxLength: 16 }),
    ),
    channels: l.optional(l.array(l.ref<ChannelRef>((() => channelRef) as any))),
  }),
)

export { plan }

/** A reference to a channel by its ID. */
type ChannelRef = {
  $type?: 'fund.at.funding.defs#channelRef'

  /**
   * The channelId of the referenced channel.
   */
  channelId: string
}

export type { ChannelRef }

/** A reference to a channel by its ID. */
const channelRef = l.typedObject<ChannelRef>(
  $nsid,
  'channelRef',
  l.object({ channelId: l.string({ maxLength: 32 }) }),
)

export { channelRef }
