/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.funding.history'

export { $nsid }

/** A single year's financial summary — income, expenses, and taxes. Supports the same transparency that funding.json history provides, but as individual ATProto records that can be listed via com.atproto.repo.listRecords. */
type Main = {
  $type: 'fund.at.funding.history'

  /**
   * The calendar year this record covers (e.g. 2024).
   */
  year: number

  /**
   * Total income received in the smallest currency unit (e.g. cents for USD).
   */
  income?: number

  /**
   * Total expenses in the smallest currency unit.
   */
  expenses?: number

  /**
   * Total taxes paid in the smallest currency unit.
   */
  taxes?: number

  /**
   * ISO 4217 currency code (e.g. 'USD', 'EUR').
   */
  currency?: string

  /**
   * Human-readable narrative for this year (e.g. 'First year accepting donations').
   */
  description?: string

  /**
   * When this record was created or last updated.
   */
  createdAt?: l.DatetimeString
}

export type { Main }

/** A single year's financial summary — income, expenses, and taxes. Supports the same transparency that funding.json history provides, but as individual ATProto records that can be listed via com.atproto.repo.listRecords. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    year: l.integer(),
    income: l.optional(l.integer()),
    expenses: l.optional(l.integer()),
    taxes: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
    description: l.optional(l.string({ maxLength: 500 })),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
