/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as FundingDefs from './defs.defs.js'

const $nsid = 'fund.at.funding.manifest'

export { $nsid }

/** Machine-readable funding manifest. Declares how people can support this entity — payment channels and optional plans with amounts. Channel and plan types are defined in fund.at.funding.defs for reuse. */
type Main = {
  $type: 'fund.at.funding.manifest'

  /**
   * Payment channels where contributions can be made.
   */
  channels: FundingDefs.Channel[]

  /**
   * Funding tiers or plans with suggested amounts.
   */
  plans?: FundingDefs.Plan[]

  /**
   * When this manifest was created or last updated.
   */
  createdAt?: l.DatetimeString
}

export type { Main }

/** Machine-readable funding manifest. Declares how people can support this entity — payment channels and optional plans with amounts. Channel and plan types are defined in fund.at.funding.defs for reuse. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    channels: l.array(
      l.ref<FundingDefs.Channel>((() => FundingDefs.channel) as any),
      { maxLength: 10 },
    ),
    plans: l.optional(
      l.array(l.ref<FundingDefs.Plan>((() => FundingDefs.plan) as any), {
        maxLength: 10,
      }),
    ),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
