/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.funding.plan'

export { $nsid }

/** A funding plan — a named tier or suggested contribution level. References payment channels by AT URI, which may be in this account or any other account's fund.at.funding.channel records. */
type Main = {
  $type: 'fund.at.funding.plan'

  /**
   * Whether this plan is currently accepting contributions. Maps to funding.json plan.status.
   */
  status?: 'active' | 'inactive' | l.UnknownString

  /**
   * Human-readable plan name (e.g. 'Supporter', 'Sustainer').
   */
  name: string

  /**
   * What this plan covers or how the funds are used.
   */
  description?: string

  /**
   * Suggested amount in the smallest currency unit (e.g. cents for USD). Use 0 for 'any amount'. Maps to funding.json plan.amount (converted from whole units).
   */
  amount?: number

  /**
   * ISO 4217 currency code (e.g. 'USD', 'EUR').
   */
  currency?: string

  /**
   * How often the plan is billed. Maps to funding.json plan.frequency.
   */
  frequency?:
    | 'one-time'
    | 'weekly'
    | 'fortnightly'
    | 'monthly'
    | 'yearly'
    | 'other'
    | l.UnknownString

  /**
   * AT URIs of fund.at.funding.channel records where this plan can be fulfilled. May reference channels in any account. If omitted, all of this account's channels apply.
   */
  channels?: l.AtUriString[]

  /**
   * When this record was created or last updated.
   */
  createdAt?: l.DatetimeString
}

export type { Main }

/** A funding plan — a named tier or suggested contribution level. References payment channels by AT URI, which may be in this account or any other account's fund.at.funding.channel records. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    status: l.optional(
      l.string<{ maxLength: 16; knownValues: ['active', 'inactive'] }>({
        maxLength: 16,
      }),
    ),
    name: l.string({ maxLength: 128 }),
    description: l.optional(l.string({ maxLength: 500 })),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
    frequency: l.optional(
      l.string<{
        maxLength: 16
        knownValues: [
          'one-time',
          'weekly',
          'fortnightly',
          'monthly',
          'yearly',
          'other',
        ]
      }>({ maxLength: 16 }),
    ),
    channels: l.optional(
      l.array(l.string({ format: 'at-uri' }), { maxLength: 10 }),
    ),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
