/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.graph.dependency'

export { $nsid }

/** A single dependency pointer. The subject is a DID (preferred) or hostname identifying the upstream entity the author depends on. */
type Main = {
  $type: 'fund.at.graph.dependency'

  /**
   * The dependency identifier: a DID (did:plc:..., did:web:...) or a hostname (example.com). DIDs are preferred for accounts with AT Protocol identity.
   */
  subject: string

  /**
   * Human-readable name for this dependency (e.g. 'Bluesky', 'AT Protocol').
   */
  label?: string

  /**
   * When this dependency was declared.
   */
  createdAt?: l.DatetimeString
}

export type { Main }

/** A single dependency pointer. The subject is a DID (preferred) or hostname identifying the upstream entity the author depends on. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    subject: l.string({ maxLength: 512 }),
    label: l.optional(l.string({ maxLength: 128 })),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
