/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.contribute'

export { $nsid }

/** Canonical contribution entry points published by a steward DID. Optionally restricted to specific domains via restrictToDomains. */
type Main = {
  $type: 'fund.at.contribute'

  /**
   * Optional allowlist of domain/hostnames for which these contribution links should be considered applicable (e.g. example.com, pds.example.com). When omitted or empty, the record is open.
   */
  restrictToDomains?: string[]
  links?: Link[]
  effectiveDate?: l.DatetimeString
}

export type { Main }

/** Canonical contribution entry points published by a steward DID. Optionally restricted to specific domains via restrictToDomains. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    restrictToDomains: l.optional(l.array(l.string())),
    links: l.optional(l.array(l.ref<Link>((() => link) as any))),
    effectiveDate: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Link = {
  $type?: 'fund.at.contribute#link'
  label: string
  url: l.UriString
}

export type { Link }

const link = l.typedObject<Link>(
  $nsid,
  'link',
  l.object({ label: l.string(), url: l.string({ format: 'uri' }) }),
)

export { link }
