/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.dependencies'

export { $nsid }

/** List of dependency identifiers (DIDs or hostnames). Optionally scoped with restrictToDomains and/or appliesToNsidPrefix. */
type Main = {
  $type: 'fund.at.dependencies'

  /**
   * Optional allowlist of domain/hostnames for which this record applies (e.g. example.com, pds.example.com). When omitted or empty, the record is open.
   */
  restrictToDomains?: string[]

  /**
   * Optional NSID prefix this dependency list applies to (e.g. app.bsky.). When omitted, the record applies generally (subject to restrictToDomains). Host-only clients typically ignore NSID-scoped records.
   */
  appliesToNsidPrefix?: string

  /**
   * Dependency identifiers. Each entry must be either a DID (did:plc:… / did:web:…) or a hostname (example.com, pds.example.com).
   */
  uris: string[]
  effectiveDate?: l.DatetimeString

  /**
   * Optional human-readable context for indexers or maintainers.
   */
  notes?: string
}

export type { Main }

/** List of dependency identifiers (DIDs or hostnames). Optionally scoped with restrictToDomains and/or appliesToNsidPrefix. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    restrictToDomains: l.optional(l.array(l.string())),
    appliesToNsidPrefix: l.optional(l.string()),
    uris: l.array(l.string()),
    effectiveDate: l.optional(l.string({ format: 'datetime' })),
    notes: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
