/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.disclosure'

export { $nsid }

/** Canonical trust and legal disclosure published by a steward DID. Optionally restricted to specific domains via restrictToDomains. */
type Main = {
  $type: 'fund.at.disclosure'

  /**
   * Optional allowlist of domain/hostnames for which this disclosure should be considered applicable (e.g. example.com, pds.example.com). When omitted or empty, the disclosure is open.
   */
  restrictToDomains?: string[]

  /**
   * When this disclosure was last meaningfully updated (policy, legal, or identity refresh).
   */
  effectiveDate?: l.DatetimeString

  /**
   * Optional AT-URI of a prior fund.at.disclosure record this entry replaces.
   */
  supersedes?: l.AtUriString

  /**
   * Public name, description, and landing page for the namespace or product.
   */
  meta?: Meta

  /**
   * Contact channels for support and press.
   */
  contact?: Contact

  /**
   * Security policy and responsible disclosure contact.
   */
  security?: Security

  /**
   * Jurisdiction, entity name, and policy URLs for donors and users.
   */
  legal?: Legal
}

export type { Main }

/** Canonical trust and legal disclosure published by a steward DID. Optionally restricted to specific domains via restrictToDomains. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    restrictToDomains: l.optional(l.array(l.string())),
    effectiveDate: l.optional(l.string({ format: 'datetime' })),
    supersedes: l.optional(l.string({ format: 'at-uri' })),
    meta: l.optional(l.ref<Meta>((() => meta) as any)),
    contact: l.optional(l.ref<Contact>((() => contact) as any)),
    security: l.optional(l.ref<Security>((() => security) as any)),
    legal: l.optional(l.ref<Legal>((() => legal) as any)),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Public name, description, and landing page for the namespace or product. */
type Meta = {
  $type?: 'fund.at.disclosure#meta'

  /**
   * Short public name of the project or namespace product.
   */
  displayName?: string

  /**
   * Plain-language, donor-facing summary.
   */
  description?: string

  /**
   * Canonical website or documentation root.
   */
  landingPage?: l.UriString
}

export type { Meta }

/** Public name, description, and landing page for the namespace or product. */
const meta = l.typedObject<Meta>(
  $nsid,
  'meta',
  l.object({
    displayName: l.optional(l.string()),
    description: l.optional(l.string()),
    landingPage: l.optional(l.string({ format: 'uri' })),
  }),
)

export { meta }

/** Contact channels for support and press. */
type Contact = {
  $type?: 'fund.at.disclosure#contact'

  /**
   * General or support contact.
   */
  general?: ContactChannel

  /**
   * Optional press or media contact, if distinct from general.
   */
  press?: PressChannel
}

export type { Contact }

/** Contact channels for support and press. */
const contact = l.typedObject<Contact>(
  $nsid,
  'contact',
  l.object({
    general: l.optional(l.ref<ContactChannel>((() => contactChannel) as any)),
    press: l.optional(l.ref<PressChannel>((() => pressChannel) as any)),
  }),
)

export { contact }

/** General or support contact. */
type ContactChannel = {
  $type?: 'fund.at.disclosure#contactChannel'

  /**
   * Atmosphere handle for the project or maintainer (e.g. example.bsky.social or a verified domain handle).
   */
  handle?: string

  /**
   * Support or general inquiries email.
   */
  email?: string

  /**
   * Contact form or support page URL.
   */
  url?: l.UriString
}

export type { ContactChannel }

/** General or support contact. */
const contactChannel = l.typedObject<ContactChannel>(
  $nsid,
  'contactChannel',
  l.object({
    handle: l.optional(l.string()),
    email: l.optional(l.string()),
    url: l.optional(l.string({ format: 'uri' })),
  }),
)

export { contactChannel }

/** Optional press or media contact. */
type PressChannel = {
  $type?: 'fund.at.disclosure#pressChannel'
  email?: string
  url?: l.UriString
}

export type { PressChannel }

/** Optional press or media contact. */
const pressChannel = l.typedObject<PressChannel>(
  $nsid,
  'pressChannel',
  l.object({
    email: l.optional(l.string()),
    url: l.optional(l.string({ format: 'uri' })),
  }),
)

export { pressChannel }

/** Security policy and responsible disclosure contact. */
type Security = {
  $type?: 'fund.at.disclosure#security'

  /**
   * URL of the security or vulnerability disclosure policy.
   */
  policyUri?: l.UriString

  /**
   * Dedicated security contact email.
   */
  contactEmail?: string

  /**
   * Security reporting form or page URL.
   */
  contactUri?: l.UriString
}

export type { Security }

/** Security policy and responsible disclosure contact. */
const security = l.typedObject<Security>(
  $nsid,
  'security',
  l.object({
    policyUri: l.optional(l.string({ format: 'uri' })),
    contactEmail: l.optional(l.string()),
    contactUri: l.optional(l.string({ format: 'uri' })),
  }),
)

export { security }

/** Jurisdiction, entity name, and policy URLs for donors and users. */
type Legal = {
  $type?: 'fund.at.disclosure#legal'

  /**
   * Human-readable jurisdiction (e.g. region or governing law).
   */
  jurisdiction?: string

  /**
   * Registered legal name of the entity receiving or governing donations, if applicable.
   */
  legalEntityName?: string

  /**
   * Terms governing use of the product or service.
   */
  termsOfServiceUri?: l.UriString

  /**
   * Privacy policy covering user and donor data.
   */
  privacyPolicyUri?: l.UriString

  /**
   * Terms specific to making a donation, if separate from general ToS.
   */
  donorTermsUri?: l.UriString

  /**
   * Page describing tax treatment of donations (e.g. charity registration), varies by region.
   */
  taxDisclosureUri?: l.UriString

  /**
   * License for software or lexicon artifacts, if distinct from donation terms.
   */
  softwareLicenseUri?: l.UriString
}

export type { Legal }

/** Jurisdiction, entity name, and policy URLs for donors and users. */
const legal = l.typedObject<Legal>(
  $nsid,
  'legal',
  l.object({
    jurisdiction: l.optional(l.string()),
    legalEntityName: l.optional(l.string()),
    termsOfServiceUri: l.optional(l.string({ format: 'uri' })),
    privacyPolicyUri: l.optional(l.string({ format: 'uri' })),
    donorTermsUri: l.optional(l.string({ format: 'uri' })),
    taxDisclosureUri: l.optional(l.string({ format: 'uri' })),
    softwareLicenseUri: l.optional(l.string({ format: 'uri' })),
  }),
)

export { legal }
