/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.manifest'

export { $nsid }

/** Machine-readable funding manifest. Declares how people can support this entity — payment channels and optional plans with amounts. */
type Main = {
  $type: 'fund.at.manifest'

  /**
   * Payment channels where contributions can be made.
   */
  channels: Channel[]

  /**
   * Optional funding tiers or plans with suggested amounts.
   */
  plans?: Plan[]

  /**
   * When this manifest was created or last updated.
   */
  createdAt?: l.DatetimeString
}

export type { Main }

/** Machine-readable funding manifest. Declares how people can support this entity — payment channels and optional plans with amounts. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    channels: l.array(l.ref<Channel>((() => channel) as any), {
      maxLength: 10,
    }),
    plans: l.optional(
      l.array(l.ref<Plan>((() => plan) as any), { maxLength: 10 }),
    ),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A single payment channel. */
type Channel = {
  $type?: 'fund.at.manifest#channel'

  /**
   * Slug identifier for this channel, unique within the manifest (e.g. 'github-sponsors', 'open-collective').
   */
  id: string

  /**
   * Channel category: 'payment-provider', 'bank', or 'other'. Defaults to 'other' if omitted.
   */
  type?: string

  /**
   * The URL or address for this channel (e.g. https://github.com/sponsors/you).
   */
  uri: l.UriString

  /**
   * Optional human-readable description of this channel.
   */
  description?: string
}

export type { Channel }

/** A single payment channel. */
const channel = l.typedObject<Channel>(
  $nsid,
  'channel',
  l.object({
    id: l.string({ maxLength: 32 }),
    type: l.optional(l.string({ maxLength: 32 })),
    uri: l.string({ format: 'uri' }),
    description: l.optional(l.string({ maxLength: 256 })),
  }),
)

export { channel }

/** A funding plan or tier with a suggested amount. */
type Plan = {
  $type?: 'fund.at.manifest#plan'

  /**
   * Slug identifier for this plan, unique within the manifest.
   */
  id: string

  /**
   * Human-readable plan name (e.g. 'Supporter', 'Sustainer').
   */
  name: string

  /**
   * Optional description of what this plan covers.
   */
  description?: string

  /**
   * Suggested amount in the smallest currency unit (e.g. cents for USD). Use 0 for 'any amount'.
   */
  amount: number

  /**
   * ISO 4217 currency code (e.g. 'USD', 'EUR').
   */
  currency: string

  /**
   * Payment frequency: 'one-time', 'monthly', 'yearly', or 'other'.
   */
  frequency: string

  /**
   * Channel IDs where this plan can be fulfilled. If omitted, all channels apply.
   */
  channels?: string[]
}

export type { Plan }

/** A funding plan or tier with a suggested amount. */
const plan = l.typedObject<Plan>(
  $nsid,
  'plan',
  l.object({
    id: l.string({ maxLength: 32 }),
    name: l.string({ maxLength: 128 }),
    description: l.optional(l.string({ maxLength: 256 })),
    amount: l.integer(),
    currency: l.string({ maxLength: 3 }),
    frequency: l.string({ maxLength: 16 }),
    channels: l.optional(l.array(l.string())),
  }),
)

export { plan }
