/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fund.at.actor.declaration'

export { $nsid }

/** The account's fund.at declaration. Create to join the ecosystem, delete to leave. A backfill service can enumerate all participants by scanning for this record. */
type Main = {
  $type: 'fund.at.actor.declaration'

  /**
   * What kind of entity this account represents. Maps to funding.json entity.type.
   */
  entityType?:
    | 'individual'
    | 'group'
    | 'collective'
    | 'organisation'
    | 'other'
    | l.UnknownString

  /**
   * The account's role relative to the projects it stewards. Maps to funding.json entity.role.
   */
  role?:
    | 'owner'
    | 'steward'
    | 'maintainer'
    | 'contributor'
    | 'sponsor'
    | 'other'
    | l.UnknownString

  /**
   * When this declaration was created or last updated.
   */
  createdAt?: l.DatetimeString
}

export type { Main }

/** The account's fund.at declaration. Create to join the ecosystem, delete to leave. A backfill service can enumerate all participants by scanning for this record. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    entityType: l.optional(
      l.string<{
        maxLength: 32
        knownValues: [
          'individual',
          'group',
          'collective',
          'organisation',
          'other',
        ]
      }>({ maxLength: 32 }),
    ),
    role: l.optional(
      l.string<{
        maxLength: 32
        knownValues: [
          'owner',
          'steward',
          'maintainer',
          'contributor',
          'sponsor',
          'other',
        ]
      }>({ maxLength: 32 }),
    ),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
